version: '2'

services:
  postgresql:
    image: postgres:9
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command:
      - postgres
      - -c
      - superuser_reserved_connections=30
      - -c
      - max_connections=1000
  digdag:
    build:
      context: .
      args:
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_NAME: ${DB_NAME}
        DIGDAG_ENCRYPTION_KEY: ${DIGDAG_ENCRYPTION_KEY}
    container_name: digdag
    volumes:
      - "./data:/var/data"
    ports:
      - "65432:65432"
      - "65433:65433"
    environment:
      WAIT_HOSTS: postgresql:${DB_PORT}